// ============================================================
//  SPORTSWARE – js/productos-data.js
//  Catálogo completo de 55 productos con tallas, ofertas y descuentos
//  CORRECCIÓN: rutas de imagen cambiadas de '/images/...' a '../images/...'
//  para funcionar correctamente desde la carpeta html/
// ============================================================

window.productos = [
  // ═══════════════════════════════════════════════════════════
  // CAMISETAS HOMBRE (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CAM-H-01',
    nombre: 'Camiseta Deportiva Hombre Nike Pro Dri-FIT',
    marca: 'Nike',
    categoria: 'camisetas',
    genero: 'hombre',
    precio: 159900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-H-01.jpg',
    descripcion: 'Tecnología Dri-FIT que absorbe el sudor para mantenerte seco. Ideal para entrenamientos intensos.',
    tallas: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 20
  },
  {
    id: 'CAM-H-02',
    nombre: 'Camiseta Hombre Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'camisetas',
    genero: 'hombre',
    precio: 139900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-H-02.jpg',
    descripcion: 'Ligera y transpirable, ideal para correr. Tecnología Climalite.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 18
  },
  {
    id: 'CAM-H-03',
    nombre: 'Camiseta Hombre Under Armour Tech 2.0',
    marca: 'Under Armour',
    categoria: 'camisetas',
    genero: 'hombre',
    precio: 129900,
    precioAntes: 169900,
    descuento: 23,
    esOferta: true,
    imagen: '../images/camisetas/CAM-H-03.jpg',
    descripcion: 'Tejido suave y de secado rápido. Perfecta para el gimnasio.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 15
  },
  {
    id: 'CAM-H-04',
    nombre: 'Camiseta Hombre Puma Deportiva Manga Corta',
    marca: 'Puma',
    categoria: 'camisetas',
    genero: 'hombre',
    precio: 109900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-H-04.jpg',
    descripcion: 'Corte clásico, algodón y poliéster. Para entrenamiento diario.',
    tallas: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 25
  },
  {
    id: 'CAM-H-05',
    nombre: 'Camiseta Hombre Reebok Training',
    marca: 'Reebok',
    categoria: 'camisetas',
    genero: 'hombre',
    precio: 119900,
    precioAntes: 149900,
    descuento: 20,
    esOferta: true,
    imagen: '../images/camisetas/CAM-H-05.jpg',
    descripcion: 'Resistente y cómoda para entrenamientos intensos. Tecnología Speedwick.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 12
  },

  // ═══════════════════════════════════════════════════════════
  // CAMISETAS MUJER (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'CAM-M-01',
    nombre: 'Camiseta Deportiva Mujer Nike Dri-FIT',
    marca: 'Nike',
    categoria: 'camisetas',
    genero: 'mujer',
    precio: 159900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-M-01.jpg',
    descripcion: 'Ajuste ligero y frescura duradera. Corte entallado.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 22
  },
  {
    id: 'CAM-M-02',
    nombre: 'Camiseta Mujer Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'camisetas',
    genero: 'mujer',
    precio: 139900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-M-02.jpg',
    descripcion: 'Malla transpirable y reflectante. Para correr con seguridad.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 19
  },
  {
    id: 'CAM-M-03',
    nombre: 'Camiseta Mujer Under Armour Tech 2.0',
    marca: 'Under Armour',
    categoria: 'camisetas',
    genero: 'mujer',
    precio: 129900,
    precioAntes: 159900,
    descuento: 18,
    esOferta: true,
    imagen: '../images/camisetas/CAM-M-03.jpg',
    descripcion: 'Suave y de secado rápido. Tecnología antiolor.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 14
  },
  {
    id: 'CAM-M-04',
    nombre: 'Camiseta Mujer Puma Deportiva',
    marca: 'Puma',
    categoria: 'camisetas',
    genero: 'mujer',
    precio: 109900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/camisetas/CAM-M-04.jpg',
    descripcion: 'Diseño ajustado y cómodo. Ideal para yoga y pilates.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 27
  },
  {
    id: 'CAM-M-05',
    nombre: 'Camiseta Mujer Reebok Training',
    marca: 'Reebok',
    categoria: 'camisetas',
    genero: 'mujer',
    precio: 119900,
    precioAntes: 139900,
    descuento: 14,
    esOferta: true,
    imagen: '../images/camisetas/CAM-M-05.jpg',
    descripcion: 'Elasticidad y libertad de movimiento. Tejido que absorbe el sudor.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 11
  },

  // ═══════════════════════════════════════════════════════════
  // LEGGINGS HOMBRE (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'LEG-H-01',
    nombre: 'Leggings Hombre Nike Pro Dri-FIT',
    marca: 'Nike',
    categoria: 'leggings',
    genero: 'hombre',
    precio: 179900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-H-01.jpg',
    descripcion: 'Compresión y soporte muscular. Tecnología Dri-FIT.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 16
  },
  {
    id: 'LEG-H-02',
    nombre: 'Leggings Hombre Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'leggings',
    genero: 'hombre',
    precio: 169900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-H-02.jpg',
    descripcion: 'Ajuste ceñido y transpirable. Bolsillo para llaves.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 13
  },
  {
    id: 'LEG-H-03',
    nombre: 'Leggings Hombre Under Armour HeatGear',
    marca: 'Under Armour',
    categoria: 'leggings',
    genero: 'hombre',
    precio: 159900,
    precioAntes: 199900,
    descuento: 20,
    esOferta: true,
    imagen: '../images/leggings/LEG-H-03.jpg',
    descripcion: 'Fresco en climas cálidos. Compresión ligera.',
    tallas: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 10
  },
  {
    id: 'LEG-H-04',
    nombre: 'Leggings Hombre Puma Training',
    marca: 'Puma',
    categoria: 'leggings',
    genero: 'hombre',
    precio: 149900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-H-04.jpg',
    descripcion: 'Elasticidad y durabilidad. Costuras planas.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 18
  },
  {
    id: 'LEG-H-05',
    nombre: 'Leggings Hombre Reebok Training',
    marca: 'Reebok',
    categoria: 'leggings',
    genero: 'hombre',
    precio: 139900,
    precioAntes: 169900,
    descuento: 17,
    esOferta: true,
    imagen: '../images/leggings/LEG-H-05.jpg',
    descripcion: 'Costuras planas para evitar rozaduras. Tejido de secado rápido.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 14
  },

  // ═══════════════════════════════════════════════════════════
  // LEGGINGS MUJER (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'LEG-M-01',
    nombre: 'Leggings Mujer Nike One Dri-FIT',
    marca: 'Nike',
    categoria: 'leggings',
    genero: 'mujer',
    precio: 179900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-M-01.jpg',
    descripcion: 'Alta cintura y sujeción. Bolsillo lateral.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 23
  },
  {
    id: 'LEG-M-02',
    nombre: 'Leggings Mujer Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'leggings',
    genero: 'mujer',
    precio: 169900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-M-02.jpg',
    descripcion: 'Transpirables y reflectantes. Para correr de noche.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 17
  },
  {
    id: 'LEG-M-03',
    nombre: 'Leggings Mujer Under Armour HeatGear',
    marca: 'Under Armour',
    categoria: 'leggings',
    genero: 'mujer',
    precio: 159900,
    precioAntes: 189900,
    descuento: 15,
    esOferta: true,
    imagen: '../images/leggings/LEG-M-03.jpg',
    descripcion: 'Ligeros y de secado rápido. Cinturilla alta.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 12
  },
  {
    id: 'LEG-M-04',
    nombre: 'Leggings Mujer Puma Training',
    marca: 'Puma',
    categoria: 'leggings',
    genero: 'mujer',
    precio: 149900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/leggings/LEG-M-04.jpg',
    descripcion: 'Ajuste perfecto para yoga. Tejido suave.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 21
  },
  {
    id: 'LEG-M-05',
    nombre: 'Leggings Mujer Reebok Training',
    marca: 'Reebok',
    categoria: 'leggings',
    genero: 'mujer',
    precio: 139900,
    precioAntes: 159900,
    descuento: 12,
    esOferta: true,
    imagen: '../images/leggings/LEG-M-05.jpg',
    descripcion: 'Resistente a las sentadillas. Tejido opaco.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 15
  },

  // ═══════════════════════════════════════════════════════════
  // TENIS HOMBRE (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'TEN-H-01',
    nombre: 'Tenis Hombre Nike Revolution 6',
    marca: 'Nike',
    categoria: 'tenis',
    genero: 'hombre',
    precio: 239900,
    precioAntes: 289900,
    descuento: 17,
    esOferta: true,
    imagen: '../images/tenis/TEN-H-01.jpg',
    descripcion: 'Amortiguación suave y duradera. Upper transpirable.',
    tallas: ['39', '40', '41', '42', '43', '44', '45'],
    stock: 20
  },
  {
    id: 'TEN-H-02',
    nombre: 'Tenis Hombre Adidas Runfalcon 3.0',
    marca: 'Adidas',
    categoria: 'tenis',
    genero: 'hombre',
    precio: 229900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-H-02.jpg',
    descripcion: 'Ligeros y flexibles. Suela de caucho.',
    tallas: ['40', '41', '42', '43', '44', '45'],
    stock: 18
  },
  {
    id: 'TEN-H-03',
    nombre: 'Tenis Hombre Under Armour Charged Assert 9',
    marca: 'Under Armour',
    categoria: 'tenis',
    genero: 'hombre',
    precio: 219900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-H-03.jpg',
    descripcion: 'Soporte y comodidad. Amortiguación Charged.',
    tallas: ['39', '40', '41', '42', '43', '44', '45', '46'],
    stock: 14
  },
  {
    id: 'TEN-H-04',
    nombre: 'Tenis Hombre Puma Smash V2',
    marca: 'Puma',
    categoria: 'tenis',
    genero: 'hombre',
    precio: 199900,
    precioAntes: 239900,
    descuento: 16,
    esOferta: true,
    imagen: '../images/tenis/TEN-H-04.jpg',
    descripcion: 'Diseño clásico de tenis. Piel sintética.',
    tallas: ['40', '41', '42', '43', '44'],
    stock: 22
  },
  {
    id: 'TEN-H-05',
    nombre: 'Tenis Hombre Reebok Nano X2',
    marca: 'Reebok',
    categoria: 'tenis',
    genero: 'hombre',
    precio: 279900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-H-05.jpg',
    descripcion: 'Para entrenamiento de alto rendimiento. Durabilidad extrema.',
    tallas: ['40', '41', '42', '43', '44', '45'],
    stock: 10
  },

  // ═══════════════════════════════════════════════════════════
  // TENIS MUJER (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'TEN-M-01',
    nombre: 'Tenis Mujer Nike Revolution 6',
    marca: 'Nike',
    categoria: 'tenis',
    genero: 'mujer',
    precio: 239900,
    precioAntes: 279900,
    descuento: 14,
    esOferta: true,
    imagen: '../images/tenis/TEN-M-01.jpg',
    descripcion: 'Amortiguación suave para correr. Colores vibrantes.',
    tallas: ['36', '37', '38', '39', '40', '41'],
    stock: 16
  },
  {
    id: 'TEN-M-02',
    nombre: 'Tenis Mujer Adidas Runfalcon 3.0',
    marca: 'Adidas',
    categoria: 'tenis',
    genero: 'mujer',
    precio: 229900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-M-02.jpg',
    descripcion: 'Ligeros y transpirables. Diseño femenino.',
    tallas: ['36', '37', '38', '39', '40', '41', '42'],
    stock: 19
  },
  {
    id: 'TEN-M-03',
    nombre: 'Tenis Mujer Under Armour Charged Assert 9',
    marca: 'Under Armour',
    categoria: 'tenis',
    genero: 'mujer',
    precio: 219900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-M-03.jpg',
    descripcion: 'Estabilidad y confort. Ideal para entrenamiento diario.',
    tallas: ['36', '37', '38', '39', '40', '41'],
    stock: 13
  },
  {
    id: 'TEN-M-04',
    nombre: 'Tenis Mujer Puma Smash V2',
    marca: 'Puma',
    categoria: 'tenis',
    genero: 'mujer',
    precio: 199900,
    precioAntes: 229900,
    descuento: 13,
    esOferta: true,
    imagen: '../images/tenis/TEN-M-04.jpg',
    descripcion: 'Estilo versátil. Combinación de gamuza y malla.',
    tallas: ['36', '37', '38', '39', '40'],
    stock: 21
  },
  {
    id: 'TEN-M-05',
    nombre: 'Tenis Mujer Reebok Nano X2',
    marca: 'Reebok',
    categoria: 'tenis',
    genero: 'mujer',
    precio: 279900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/tenis/TEN-M-05.jpg',
    descripcion: 'Durabilidad extrema. Para crossfit y entrenamiento funcional.',
    tallas: ['36', '37', '38', '39', '40', '41', '42'],
    stock: 9
  },

  // ═══════════════════════════════════════════════════════════
  // ACCESORIOS HOMBRE (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ACC-H-01',
    nombre: 'Gorra Deportiva Hombre Nike Dri-FIT',
    marca: 'Nike',
    categoria: 'accesorios',
    genero: 'hombre',
    precio: 89900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-H-01.jpg',
    descripcion: 'Absorbe el sudor, ajuste cómodo. Cierre trasero ajustable.',
    tallas: ['Único'],
    stock: 35
  },
  {
    id: 'ACC-H-02',
    nombre: 'Muñequeras Deportivas Hombre Adidas (Par)',
    marca: 'Adidas',
    categoria: 'accesorios',
    genero: 'hombre',
    precio: 49900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-H-02.jpg',
    descripcion: 'Algodón, absorben sudor. Pack de 2 unidades.',
    tallas: ['Único'],
    stock: 50
  },
  {
    id: 'ACC-H-03',
    nombre: 'Gorra Hombre Under Armour Blitzing',
    marca: 'Under Armour',
    categoria: 'accesorios',
    genero: 'hombre',
    precio: 79900,
    precioAntes: 99900,
    descuento: 20,
    esOferta: true,
    imagen: '../images/accesorios/ACC-H-03.jpg',
    descripcion: 'Ligera y transpirable. Paneles de malla.',
    tallas: ['Único'],
    stock: 28
  },
  {
    id: 'ACC-H-04',
    nombre: 'Riñonera Hombre Puma',
    marca: 'Puma',
    categoria: 'accesorios',
    genero: 'hombre',
    precio: 69900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-H-04.jpg',
    descripcion: 'Pequeña, para correr. Bolsillo frontal con cremallera.',
    tallas: ['Único'],
    stock: 40
  },
  {
    id: 'ACC-H-05',
    nombre: 'Gorra Hombre Reebok Training',
    marca: 'Reebok',
    categoria: 'accesorios',
    genero: 'hombre',
    precio: 79900,
    precioAntes: 89900,
    descuento: 11,
    esOferta: true,
    imagen: '../images/accesorios/ACC-H-05.jpg',
    descripcion: 'Ajuste trasero, diseño deportivo. Tejido de secado rápido.',
    tallas: ['Único'],
    stock: 32
  },

  // ═══════════════════════════════════════════════════════════
  // ACCESORIOS MUJER (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ACC-M-01',
    nombre: 'Gorra Deportiva Mujer Nike Dri-FIT',
    marca: 'Nike',
    categoria: 'accesorios',
    genero: 'mujer',
    precio: 89900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-M-01.jpg',
    descripcion: 'Ligera y fresca. Colores pastel.',
    tallas: ['Único'],
    stock: 30
  },
  {
    id: 'ACC-M-02',
    nombre: 'Muñequeras Deportivas Mujer Adidas (Par)',
    marca: 'Adidas',
    categoria: 'accesorios',
    genero: 'mujer',
    precio: 49900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-M-02.jpg',
    descripcion: 'Suaves y absorbentes. Lavables a máquina.',
    tallas: ['Único'],
    stock: 45
  },
  {
    id: 'ACC-M-03',
    nombre: 'Visera Mujer Under Armour',
    marca: 'Under Armour',
    categoria: 'accesorios',
    genero: 'mujer',
    precio: 69900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/accesorios/ACC-M-03.jpg',
    descripcion: 'Protección solar, ajuste elástico. Cinta interior que absorbe el sudor.',
    tallas: ['Único'],
    stock: 25
  },
  {
    id: 'ACC-M-04',
    nombre: 'Riñonera Mujer Puma',
    marca: 'Puma',
    categoria: 'accesorios',
    genero: 'mujer',
    precio: 69900,
    precioAntes: 79900,
    descuento: 12,
    esOferta: true,
    imagen: '../images/accesorios/ACC-M-04.jpg',
    descripcion: 'Compacta y resistente al agua. Varios compartimentos.',
    tallas: ['Único'],
    stock: 38
  },
  {
    id: 'ACC-M-05',
    nombre: 'Diadema Deportiva Mujer Reebok (Pack 3)',
    marca: 'Reebok',
    categoria: 'accesorios',
    genero: 'mujer',
    precio: 39900,
    precioAntes: 59900,
    descuento: 33,
    esOferta: true,
    imagen: '../images/accesorios/ACC-M-05.jpg',
    descripcion: 'Pack de 3 colores, antideslizante. Tejido suave.',
    tallas: ['Único'],
    stock: 60
  },

  // ═══════════════════════════════════════════════════════════
  // SHORTS HOMBRE (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SHO-H-01',
    nombre: 'Short Hombre Nike Dri-FIT',
    marca: 'Nike',
    categoria: 'shorts',
    genero: 'hombre',
    precio: 129900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-H-01.jpg',
    descripcion: 'Tejido de malla, interior tipo licra. Bolsillos laterales.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 20
  },
  {
    id: 'SHO-H-02',
    nombre: 'Short Hombre Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'shorts',
    genero: 'hombre',
    precio: 119900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-H-02.jpg',
    descripcion: 'Con bolsillo para llaves. Cinturilla elástica.',
    tallas: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 18
  },
  {
    id: 'SHO-H-03',
    nombre: 'Short Hombre Under Armour Tech',
    marca: 'Under Armour',
    categoria: 'shorts',
    genero: 'hombre',
    precio: 109900,
    precioAntes: 139900,
    descuento: 21,
    esOferta: true,
    imagen: '../images/shorts/SHO-H-03.jpg',
    descripcion: 'Ligeros y de secado rápido. Forro interior.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 14
  },
  {
    id: 'SHO-H-04',
    nombre: 'Short Hombre Puma Deportivo',
    marca: 'Puma',
    categoria: 'shorts',
    genero: 'hombre',
    precio: 99900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-H-04.jpg',
    descripcion: 'Corte holgado, cintura elástica. Con cordón.',
    tallas: ['S', 'M', 'L', 'XL'],
    stock: 25
  },
  {
    id: 'SHO-H-05',
    nombre: 'Short Hombre Reebok Training',
    marca: 'Reebok',
    categoria: 'shorts',
    genero: 'hombre',
    precio: 99900,
    precioAntes: 119900,
    descuento: 16,
    esOferta: true,
    imagen: '../images/shorts/SHO-H-05.jpg',
    descripcion: 'Resistente a la abrasión. Tejido elástico.',
    tallas: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 16
  },

  // ═══════════════════════════════════════════════════════════
  // SHORTS MUJER (5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SHO-M-01',
    nombre: 'Short Mujer Nike Dri-FIT',
    marca: 'Nike',
    categoria: 'shorts',
    genero: 'mujer',
    precio: 129900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-M-01.jpg',
    descripcion: 'Corte corto, interior integrado. Cinturilla alta.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 22
  },
  {
    id: 'SHO-M-02',
    nombre: 'Short Mujer Adidas Own the Run',
    marca: 'Adidas',
    categoria: 'shorts',
    genero: 'mujer',
    precio: 119900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-M-02.jpg',
    descripcion: 'Con reflectivos para correr de noche. Bolsillo interior.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 17
  },
  {
    id: 'SHO-M-03',
    nombre: 'Short Mujer Under Armour Tech',
    marca: 'Under Armour',
    categoria: 'shorts',
    genero: 'mujer',
    precio: 109900,
    precioAntes: 129900,
    descuento: 15,
    esOferta: true,
    imagen: '../images/shorts/SHO-M-03.jpg',
    descripcion: 'Ultra ligeros. Forro interior de malla.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 13
  },
  {
    id: 'SHO-M-04',
    nombre: 'Short Mujer Puma Deportivo',
    marca: 'Puma',
    categoria: 'shorts',
    genero: 'mujer',
    precio: 99900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/shorts/SHO-M-04.jpg',
    descripcion: 'Cintura alta, suave al tacto. Para yoga y pilates.',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 24
  },
  {
    id: 'SHO-M-05',
    nombre: 'Short Mujer Reebok Training',
    marca: 'Reebok',
    categoria: 'shorts',
    genero: 'mujer',
    precio: 99900,
    precioAntes: 109900,
    descuento: 9,
    esOferta: true,
    imagen: '../images/shorts/SHO-M-05.jpg',
    descripcion: 'Elástico y cómodo. Tejido de secado rápido.',
    tallas: ['XS', 'S', 'M', 'L'],
    stock: 19
  },

  // ═══════════════════════════════════════════════════════════
  // SUPLEMENTOS (NEUTRO – 5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'SUP-01',
    nombre: 'Proteína Whey Gold Standard (2 lbs)',
    marca: 'Optimum Nutrition',
    categoria: 'suplementos',
    genero: 'neutro',
    precio: 189900,
    precioAntes: 239900,
    descuento: 20,
    esOferta: true,
    imagen: '../images/suplementos/SUP-01.jpg',
    descripcion: 'Proteína de suero de leche, 24g por porción. Sabor chocolate.',
    tallas: ['2 lb'],
    stock: 45
  },
  {
    id: 'SUP-02',
    nombre: 'Creatina Monohidratada 300g',
    marca: 'Elite Supplements',
    categoria: 'suplementos',
    genero: 'neutro',
    precio: 124900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/suplementos/SUP-02.jpg',
    descripcion: 'Aumenta fuerza y rendimiento. Sin sabor.',
    tallas: ['300 g'],
    stock: 50
  },
  {
    id: 'SUP-03',
    nombre: 'Aminoácidos BCAA (200 cápsulas)',
    marca: 'Universal Nutrition',
    categoria: 'suplementos',
    genero: 'neutro',
    precio: 99900,
    precioAntes: 129900,
    descuento: 23,
    esOferta: true,
    imagen: '../images/suplementos/SUP-03.jpg',
    descripcion: 'Previene el catabolismo muscular. Relación 2:1:1.',
    tallas: ['200 cápsulas'],
    stock: 38
  },
  {
    id: 'SUP-04',
    nombre: 'Multivitamínico Deportivo (60 tabletas)',
    marca: 'Animal Pak',
    categoria: 'suplementos',
    genero: 'neutro',
    precio: 149900,
    precioAntes: null,
    descuento: 0,
    esOferta: false,
    imagen: '../images/suplementos/SUP-04.jpg',
    descripcion: 'Vitaminas y minerales para deportistas. Paquete completo.',
    tallas: ['60 tabletas'],
    stock: 30
  },
  {
    id: 'SUP-05',
    nombre: 'Proteína Vegana (1.5 lbs)',
    marca: 'Plant-Based',
    categoria: 'suplementos',
    genero: 'neutro',
    precio: 159900,
    precioAntes: 189900,
    descuento: 15,
    esOferta: true,
    imagen: '../images/suplementos/SUP-05.jpg',
    descripcion: 'Mezcla de guisante y arroz, sabor chocolate. Sin lácteos.',
    tallas: ['1.5 lb'],
    stock: 28
  }
];
